### ISSUE TITLE
No /etc/init.d

### ISSUE THREAD

**Issue by ghost** [K4YT3X/SCUTUM#6]
I was using an old version of scutum, so today I removed it, and tried to install 2.6.2 with sudo python3 scutum.py  --install

However the install process dies with the following error message on my arch linux (systemd):

FileNotFoundError: [Errno 2] No such file or directory: '/etc/init.d/scutum'

**Comment by fcafra** [comment]
@bryce-lynch 
Me too, but the first op is 
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/scutum/scutum'
then
shutil.copyfile("/usr/share/scutum/scutum", "/etc/init.d/scutum") ...

you can create manually mkdir /usr/share/scutum/ and copy scutum to /usr/share/scutum/ and retry.

**Comment by ghost** [comment]
@fcafra 
I already created /usr/share/scutum and copied scutum in it, that's why it's not giving me the first error you mentioned, but now it complains about /etc/init.d/scutum (I wonder why it absolutely needs the init.d directory on systemd)

**Comment by fcafra** [comment]
@bryce-lynch   

I think this, 
the pyton script failed to runinng this 
shutil.copyfile("/usr/share/scutum/scutum", "/etc/init.d/scutum") 

so, if you already copied scutum into dir  "/usr/share/scutum/"  you can launch sudo python3 scutum.py --install  without any error (for me works)

**Comment by ghost** [comment]
@fcafra 
Actually it fails because there is no init.d destination directory. I could easily create it, but I'd prefer if the author made scutum systemd-aware, rather than faking an init.d system.

**Comment by fcafra** [comment]
@bryce-lynch Ok i agree with you.

**Comment by k4yt3x** [comment]
@bryce-lynch 
Sorry for replying late.
Yes I need to adapt to various of system environments. I'm not familiar with Arch Linux as you know from before.

**Here's how SCUTUM service works:**
~~~~
1. It creates /etc/init.d/scutum
1. Registers itself with update-rc.d
1. Enables SCUTUM service using systemctl (which is for a debian based system)
1. Everytime system boots the init script starts scutum
~~~~

As you can see, the service system is created for Debian. You don't really need this to make this work, but for a system with systemd this would be pretty nice since you can control scutum with systemctl or service command.

You can though, control scutum directly using the scutum command. However, I think I should leave an option for that when the application is being installed. This should increase the compatibility.

I will look into the syetem structure of Arch Linux, but it would be helpful if you can tell me about Arch.

For now, I'll say just create the folder temporarily and finish the installation. SCUTUM will not touch that foulder again after the installation. However If you encounter issues with update-rc.d, you'll probably have to wait for a little until I solve it. 
I'll try doing it fast though.

Thank you for your support.

**Comment by ghost** [comment]
@K4YT3X 
Actually the difference is not specific to Arch Linux, but to any Linux distro using systemd instead of SysV (init.d).

Basically, if path /etc/init.d doesn't exist, the script is probably running on a systemd-based linux: you can verify either by checking if /usr/lib/systemd exists or if "pidof systemd" returns a value.

For an overview of systemd service files see https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files and https://wiki.archlinux.org/index.php/systemd

So, assuming scutum has already been copied in /usr/share/scutum/ and you're on systemd, skip the part where you copy scutum into init.d, and just create /usr/lib/systemd/system/scutum.service with something like this:

[Unit]
Description=Scutum service file
ConditionPathExists=/usr/share/scutum
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/share/scutum/scutum start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target

then execute:

`cd /etc/systemd/system/multi-user.target.wants`
`ln -s /usr/lib/systemd/system/scutum.service scutum.service`
`systemctl enable scutum.service`
`systemctl start scutum.service`

This only makes scutum start as a service, you still need to adapt scutum to the new paths, etc. Hope it helps.

**Comment by k4yt3x** [comment]
@bryce-lynch Thanks a lot for the information. I'll look into it.
I had that Arch VM before. Can't remember where I put it.

I'll verify it on my VM before releasing the new version.

**Comment by k4yt3x** [comment]
@bryce-lynch I looked into Arch Linux systemd. It is quite different from debian. That explains why you asked about the unit file before. On debian, you don't need the unit file to register a service. All you need is an executable file/script in the init.d folder and then update-rc.d to register the service.

This will add the service to the systemctl list. From then on, the service could be controlled by systemd.
Apparently, Arch does this in a different way. I'll take the unit file you've written and write a method to differentiate the two types of systemds

**Comment by k4yt3x** [comment]
@bryce-lynch Here. It's working on (at least my) Arch
![screenshot_20180128_161343](https://user-images.githubusercontent.com/21986859/35487158-97bd79ca-0446-11e8-8552-f2f3330c51d5.png)

**Comment by k4yt3x** [comment]
@bryce-lynch uploaded a new version of SCUTUM. Try installing the newest version.
Also, @fcafra, you can now choose the installation path in the newest version of SCUTUM.

There should be no more FileNotFounds

**Comment by fcafra** [comment]
I just installed (on Kali) the newer Version 2.6.3 without any issue.   

Thanks a lot.

**Comment by ghost** [comment]
@K4YT3X 
Works fine here - thanks so much!
Also I'd appreciate if you could add a configuration option to make it non-verbose (no "succeed" messages on startup/shutdown).
I'm closing this issue. Thanks again.

**Comment by fcafra** [comment]
Thank you  @bryce-lynch and @K4YT3X.
Only one question, i could add a configuration option but tell me please how. (sorry, i don't understand very well)

**Comment by ghost** [comment]
@fcafra 
When system is starting I see this debug info:

`[+] INFO: Installing for NetworkManager`

and a similar one when shutting down.

It's probably useful for most users, but it would be nice if installer.py asked if these notices should be displayed or not (where it asks the user about ufw, easy tcp controllers, etc). But if it's too much work don't worry.

**Comment by k4yt3x** [comment]
@bryce-lynch These are just print statements, same as what you see if you used the "scutum" command instead of using systemctl/service. These would be what comes out on the stdout.

However I do remember making a machenism for distinguishing between being called by a script or ran directly by a user from commandline, so sure I'll look into it and potentially make a **--quiet** switch.

By the way you're welcome. If no one ever raises issues, this program would never improve.

**Best,**
**K4YT3X**
